# Generated by Django 5.2.4 on 2025-07-28 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=10)),
                ('workplace', models.CharField(max_length=100)),
                ('department', models.CharField(choices=[('Computer Science', 'Computer Science'), ('Information Technology', 'Information Technology'), ('Electronics & Communication', 'Electronics & Communication'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Civil Engineering', 'Civil Engineering'), ('Electrical Engineering', 'Electrical Engineering'), ('Business Administration', 'Business Administration'), ('Mathematics', 'Mathematics'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('English', 'English'), ('Economics', 'Economics'), ('Psychology', 'Psychology'), ('Other', 'Other')], max_length=50)),
                ('custom_department', models.CharField(blank=True, default='', max_length=128)),
                ('workplacename', models.CharField(max_length=100)),
                ('experience', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('resume', models.FileField(upload_to='resumes/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
